@extends('humo::xml')
@section('body')
    <SOAP-ENV:Body>
        <urn:CancelRequest>
            @if(isset($payment_id))
                <paymentID>{{$payment_id}}</paymentID>
            @else
                <paymentRef>{{$payment_ref}}</paymentRef>
            @endif
            <paymentOriginator>{{$originator}}</paymentOriginator>
        </urn:CancelRequest>
    </SOAP-ENV:Body>
@endsection
